services:

  garagehub-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garagehub-api
    ports:
      - "8080:8080"

  garagehub-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: garagehub-frontend
    ports:
      - "80:80"
    depends_on:
      - garagehub-api