services:

  garagehub-api:
    image: garagehub-api
    container_name: garagehub-api
    ports:
      - "8080:8080"

  garagehub-frontend:
    image: garagehub-frontend
    container_name: garagehub-frontend
    ports:
      - "80:80"
    depends_on:
      - garagehub-api